version: "3.8"

services:
    app:
        image: thecodingmachine/php:8.0-v4-apache
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www/html
        environment:
            PHP_EXTENSION_IGBINARY: "1"
            PHP_EXTENSION_INTL: "1"
            PHP_EXTENSION_PGSQL: "1"
            PHP_EXTENSION_PDO_PGSQL: "1"
            PHP_EXTENSION_REDIS: "1"
            PHP_EXTENSION_GD: "1"
            PHP_EXTENSION_XDEBUG: "1"
            PHP_INI_MEMORY_LIMIT: "1G"
            PHP_INI_XDEBUG__IDEKEY: "PHPSTORM"
            APACHE_DOCUMENT_ROOT: "public/"
        depends_on:
            - postgres
    postgres:
        image: postgres:15.1-alpine3.16
        environment:
            POSTGRES_DB: polldb
            POSTGRES_USER: user
            POSTGRES_PASSWORD: secret
            POSTGRES_INITDB_ARGS: "--locale=ru_RU.utf8"
        ports:
            - "5433:5432"
        volumes:
            - postgres-data:/var/lib/postgresql/data

    adminer:
        image: adminer:latest
        ports:
            - "8081:8080"
volumes:
    postgres-data:
