name: Deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  CD_PART:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.USERNAME}}
          port: ${{secrets.PORT}}
          key: ${{secrets.SSHKEY}}
          command: |
            echo "Deployment started ...";
            cd /var/www/uniplay/data/www/unipoll.sbox.1gt.ru/;
            (php artisan down) || true;
            git pull origin master;
            composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader;
            php artisan clear-compiled;
            php artisan optimize;
            php artisan migrate --force;
            php artisan up;
            echo "Deployment finished!";

